/*Listar bd del servidor*/
show DATABASEs;

/*Eliminar bd alquiler*/
DROP TABLE ubigeo_codubi;

/*Crear nustra bd alquiler teniendo en cuenta la configuracion de caracteres*/
CREATE DATABASE dbalquiler DEFAULT CHARACTER set utf8;

/*Poner en uso la base de datos*/
USE dbalquiler;

/*Verificar que la bd este en usu*/
SELECT DATABASE();

/*mostrar tabla*/
show tables;

/*crear la tabla Persona*/
CREATE TABLE Persona
(
    CODPER int,
    NOMPER VARCHAR(100),
    APEPAPER VARCHAR(100),
    APEMAPER VARCHAR(100),
    DNIPER CHAR(8),
    DIRPER VARCHAR(100),
    UBIGEO_CODUBI CHAR(6),
    TELEF1PER CHAR(9),
    TELEF2PER CHAR(9),
    SEXPER CHAR(1),
    TIPPER CHAR(1),
    USUPER VARCHAR(50),
    PASPER VARCHAR(50),
    CONSTRAINT COOPPER_PK PRIMARY KEY (CODPER)
);

/*verificar la estructura de la tabla persona*/
show COLUMNs in Persona;

/*crar la tabla ubigeo*/
CREATE TABLE UBIGEO
(
    CODUBI CHAR(6),
    DISUBI VARCHAR(100),
    PROUBI VARCHAR(100),
    DEPUBI VARCHAR(100),
    CONSTRAINT CODUBI_PK PRIMARY KEY (CODUBI)
);

/*verificar la estructura de la tabla UBIGEO*/

show COLUMNs in ubigeo;

/*Creamos la tabla ubigeo*/
CREATE TABLE VIVIENDA
(
    CODVIV INT,
    DESCVIV VARCHAR(100),
    DIRVIV VARCHAR(100),
    UBIGEO_CODUBI CHAR(6),
    ESTADOVIVIENDA_CODESTVIV INT,
    TIPOVIVIENDA_CODCODTIPVIV INT,
    CONSTRAINT CODVIV_PK PRIMARY KEY (CODVIV)
);

/*Verificar estructura de la tabla vivienda*/
show COLUMNs in VIVIENDA;

/*CREAR TABLA DE ESTADO VIVIENDA*/
CREATE TABLE ESTADO_VIVIENDA
(
    CODESTVIV INT,
    DESCESTVIV VARCHAR(50),
    CONSTRAINT CODESTVIV_PK PRIMARY KEY (CODESTVIV)
);

/*CREAR LA TABLA TIPO VIVIENDA*/
CREATE TABLE TIPO_VIVIENDA
(
    CODTIPVIV INT,
    DESCTIPVIV VARCHAR(50),
CREATE TABLE ALQUILER
(
    CODALQ INT,
    FECINIALQ DATE,
    PERSONA_PROP INT,
    PERSONA_INQ INT,
    CONSTRAINT CODALQ_PK PRIMARY KEY (CODALQ)
);

/*CREAR LA TABLA DETALLE ALQUILER*/
CREATE TABLE DETALLE_ALQUILER
(
    CODDETALQ INT,
    VIVIENDA_CODVIV INT,
    FECINIDETALQ DATE,
    COSDETAL DECIMAL(8,2),
    ALQUILER_CODALQ INT,
    CONSTRAINT CODDETALQ_PK PRIMARY KEY (CODDETALQ)
    CONSTRAINT CODTIPVIV_PK PRIMARY KEY (CODTIPVIV)
);

SHOW TABLES;

/*CREAR UNA TABLA ALQUILER*/
